services:
  db:
    image: postgres:16-alpine
    container_name: aequivault-postgres
    environment:
      POSTGRES_DB: aequivault
      POSTGRES_USER: aequivault_user
      POSTGRES_PASSWORD: aequivault_pass
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aequivault_user -d aequivault"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
    driver: local
