spring.application.name=backend

# Configuración del Datasource (Inquilino no superusuario para RLS)
spring.datasource.url=jdbc:postgresql://localhost:5433/aequivault?stringtype=unspecified
spring.datasource.username=aequivault_app
spring.datasource.password=aequivault_app_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Configuración de Liquibase (Superusuario para DDL)
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true
spring.liquibase.user=aequivault_user
spring.liquibase.password=aequivault_pass

